name: Android Instrumented Tests
run-name: Instrumented Tests
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: API ${{ matrix.api-level }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        api-level: [ 30, 33, 35 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # Descarga dependencias y genera APKs de test
      - name: Assemble app and test APKs
        run: |
          ./gradlew --no-daemon --stacktrace \
            :core:presentation:assembleDebug :core:presentation:assembleAndroidTest \
            :core:data:assembleDebug :core:data:assembleAndroidTest

      - name: Run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis
          arch: x86_64
          profile: pixel_6
          ram-size: 4096M
          emulator-options: >-
            -no-snapshot -no-window -no-boot-anim -gpu swiftshader_indirect
          disable-animations: true
          script: |
            adb logcat -c
            ./gradlew --no-daemon --stacktrace \
              :core:presentation:connectedDebugAndroidTest \
              :core:data:connectedDebugAndroidTest

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: androidTest-reports-api-${{ matrix.api-level }}
          path: |
            core/presentation/build/reports/androidTests/connected/**
            core/presentation/build/outputs/androidTest-results/**/*
            core/data/build/reports/androidTests/connected/**
            core/data/build/outputs/androidTest-results/**/*