name: Unit Tests
run-name: Unit Tests
on:
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: run tests
        run: ./gradlew testReleaseUnitTest