name: Unit Tests
run-name: Unit Tests
on:
  pull_request:
    branches: [ main, develop ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4


      - name: Restore google-services.json
        run: |
          mkdir -p app
          echo "${{ secrets.FIREBASE_GOOGLE_SERVICES_JSON }}" | base64 -d > app/google-services.json

      - name: run tests
        run: ./gradlew testReleaseUnitTest
